sensor:
  - platform: statistics
    name: "Outdoor Luminosity"
    unique_id: outdoor_luminosity
    entity_id: sensor.roof_terrace_sensor_illuminance
    state_characteristic: mean
    max_age:
      minutes: 5
    precision: 0
  - platform: statistics
    name: "Outdoor Temperature Max"
    unique_id: outdoor_temperature_max
    entity_id: sensor.roof_terrace_sensor_apparent_temperature
    state_characteristic: value_max
    max_age:
      hours: 96
    precision: 2
  - platform: statistics
    name: "Outdoor Temperature Min"
    unique_id: outdoor_temperature_min
    entity_id: sensor.roof_terrace_sensor_apparent_temperature
    state_characteristic: value_min
    max_age:
      hours: 168
    precision: 2

climate:
  - platform: generic_thermostat
    name: Bathroom Heating
    unique_id: bathroom_heating
    heater: switch.bathroom_heating
    target_sensor: sensor.bathroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Gameroom Heating
    unique_id: gameroom_heating
    heater: switch.gameroom_heating
    target_sensor: sensor.gameroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Office Heating
    unique_id: office_heating
    heater: switch.office_heating
    target_sensor: sensor.office_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Gym Heating
    unique_id: gym_heating
    heater: switch.gym_heating
    target_sensor: sensor.gym_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Bedroom Heating
    unique_id: bedroom_heating
    heater: switch.bedroom_heating
    target_sensor: sensor.bedroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Living Room Heating
    unique_id: living_room_heating
    heater: switch.living_room_heating
    target_sensor: sensor.living_room_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
schedule:
  bathroom_climate:
    name: "Bathroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
  gameroom_climate:
    name: "Gameroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "18:00:00"
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
    friday:
      - from: "06:00:00"
        to: "18:00:00"
  office_climate:
    name: "Office Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "18:00:00"
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
    friday:
      - from: "06:00:00"
        to: "18:00:00"
  gym_climate:
    name: "Gym Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
  bedroom_climate:
    name: "Bedroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
  living_room_climate:
    name: "Living Room Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    saturday:
      - from: "06:00:00"
        to: "24:00:00"
    sunday:
      - from: "06:00:00"
        to: "24:00:00"
template:
  - sensor:
      - name: "Cooling"
        unique_id: cooling
        state: >
          {% set climates = [
            states('climate.gameroom_cooling'),
            states('climate.office_cooling'),
            states('climate.bedroom_cooling'),
            states('climate.living_room_cooling'),
          ] %}
          {{ climates | select('eq', 'cool') | list | count }}
        icon: mdi:snowflake-thermometer
  - sensor:
      - name: "Heating"
        unique_id: heating
        icon: mdi:sun-thermometer
        state: >
          {% set climates = [
            states('climate.bathroom_heating'),
            states('climate.gameroom_heating'),
            states('climate.office_heating'),
            states('climate.gym_heating'),
            states('climate.bedroom_heating'),
            states('climate.living_room_heating'),
          ] %}
          {{ climates | select('eq', 'heat') | list | count }}
  - sensor:
      - name: "Daylight Duration"
        unique_id: daylight_duration
        unit_of_measurement: "h"
        state_class: measurement
        state: >
          {% set sunrise = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
          {% set sunset = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
          {% if sunrise < sunset %}
            {{ ((sunset - sunrise) / 3600) | round(2) }}
          {% else %}
            {{ ((sunset + 86400 - sunrise) / 3600) | round(2) }}
          {% endif %}
        icon: mdi:sun-clock
  - sensor:
      - name: "Climate Luminosity"
        unique_id: climate_luminosity
        state: >
          {% set lux = states('sensor.outdoor_luminosity') | int(0) %}
          {% if lux < 1000 %}
            dark
          {% elif lux < 5000 %}
            low
          {% elif lux < 20000 %}
            mid
          {% elif lux < 50000 %}
            high
          {% else %}
            peak
          {% endif %}
        icon: mdi:white-balance-sunny
  - sensor:
      - name: "Climate Mode"
        unique_id: climate_mode
        state: >
          {% set hs = states('sensor.roof_terrace_sensor_heat_stress') | float(0) %}
          {% set humidex = states('sensor.roof_terrace_sensor_humidex') | float(0) %}
          {% set daylight_h = states('sensor.daylight_duration') | float(0) %}
          {% set min7 = states('sensor.outdoor_temperature_min') | float(0) %}
          {% set max4 = states('sensor.outdoor_temperature_max') | float(0) %}

          {% set warm_enter_humidex = 29 %}
          {% set warm_exit_humidex  = 27 %}
          {% set warm_enter_hs = 75 %}
          {% set warm_exit_hs  = 65 %}
          {% set cold_enter_humidex = 17 %}
          {% set cold_exit_humidex  = 19 %}
          {% set cold_enter_hs = 25 %}
          {% set cold_exit_hs  = 35 %}

          {% set last = states('sensor.climate_mode') | lower %}
          {% if last in ['unknown','unavailable','none',''] %}
            {% set last = 'mild' %}
          {% endif %}

          {% if last == 'warm' %}
            {% if (humidex <= warm_exit_humidex and hs <= warm_exit_hs) %}
              {% if humidex <= cold_enter_humidex and hs <= cold_enter_hs and min7 <= 10 %}
                cold
              {% else %}
                mild
              {% endif %}
            {% else %}
              warm
            {% endif %}

          {% elif last == 'cold' %}
            {% if (humidex >= cold_exit_humidex or hs >= cold_exit_hs) %}
              {% if (humidex >= warm_enter_humidex or hs >= warm_enter_hs)
                    and max4 >= 25
                    and daylight_h > 13 %}
                warm
              {% else %}
                mild
              {% endif %}
            {% else %}
              cold
            {% endif %}

          {% else %}
            {% if (humidex >= warm_enter_humidex or hs >= warm_enter_hs)
                  and max4 >= 25
                  and daylight_h > 13 %}
              warm
            {% elif humidex <= cold_enter_humidex and hs <= cold_enter_hs and min7 <= 10 %}
              cold
            {% else %}
              mild
            {% endif %}
          {% endif %}
        icon: mdi:sun-snowflake-variant
  - weather:
      - name: "Roof Terrace"
        unique_id: roof_terrace
        condition_template: "{{ states('sensor.roof_terrace_sensor_weather_condition') }}"
        temperature_template: "{{ states('sensor.roof_terrace_sensor_temperature') | float(0) }}"
        apparent_temperature_template: "{{ states('sensor.roof_terrace_sensor_apparent_temperature') | float(0) }}"
        humidity_template: "{{ states('sensor.roof_terrace_sensor_humidity') | float(0) }}"
        pressure_template: "{{ states('sensor.roof_terrace_sensor_pressure') | float(0) }}"
        wind_speed_template: "{{ (states('sensor.roof_terrace_sensor_wind_speed') | float(0) * 3.6) | round(1) }}"
        wind_gust_speed_template: "{{ (states('sensor.roof_terrace_sensor_gust_speed') | float(0) * 3.6) | round(1) }}"
        wind_bearing_template: "{{ states('sensor.roof_terrace_sensor_wind_direction') | float(0) }}"
        dew_point_template: "{{ states('sensor.roof_terrace_sensor_dew_point') | float(0) }}"
        wind_speed_unit: "km/h"
        pressure_unit: "hPa"
        temperature_unit: "°C"
        precipitation_unit: "mm"
        forecast_hourly_template: >
          {% set current = states('sensor.roof_terrace_sensor_weather_condition') %}
          {% set trend = states('sensor.roof_terrace_sensor_pressure_trend') | float(0) %}
          {% set temp = states('sensor.roof_terrace_sensor_temperature') | float(0) %}
          {% set humidity = states('sensor.roof_terrace_sensor_humidity') | float(0) %}

          {# Historical temperature range for diurnal curve #}
          {% set t_max = states('sensor.outdoor_temperature_max') | float(temp) %}
          {% set t_min = states('sensor.outdoor_temperature_min') | float(temp) %}
          {% set t_mean = (t_max + t_min) / 2 %}
          {% set t_amp = (t_max - t_min) / 2 %}

          {# Sun times for day/night detection #}
          {% set next_rise = state_attr('sun.sun', 'next_rising') | as_datetime %}
          {% set next_set = state_attr('sun.sun', 'next_setting') | as_datetime %}
          {% set sun_up = states('sun.sun') == 'above_horizon' %}

          {# Condition ranking: 0=worst to 4=best #}
          {% set conditions = ['pouring', 'rainy', 'cloudy', 'partlycloudy', 'sunny'] %}
          {% set night_conditions = ['pouring', 'rainy', 'cloudy', 'partlycloudy', 'clear-night'] %}
          {% set current_map = {
            'pouring': 0, 'hail': 0, 'snowy': 1,
            'rainy': 1,
            'cloudy': 2,
            'partlycloudy': 3, 'windy-variant': 3,
            'sunny': 4, 'clear-night': 4, 'windy': 4
          } %}
          {% set current_rank = current_map.get(current, 2) %}

          {# Pressure trend → condition shift per hour #}
          {% if trend > 2 %}
            {% set shift_per_hour = 0.5 %}
          {% elif trend > 0.5 %}
            {% set shift_per_hour = 0.25 %}
          {% elif trend < -2 %}
            {% set shift_per_hour = -0.5 %}
          {% elif trend < -0.5 %}
            {% set shift_per_hour = -0.25 %}
          {% else %}
            {% set shift_per_hour = 0 %}
          {% endif %}

          {# Generate 6-hour forecast #}
          {% set forecast = namespace(items=[]) %}
          {% for hour in range(1, 7) %}
            {% set future_time = now() + timedelta(hours=hour) %}

            {# Day/night detection #}
            {% if sun_up %}
              {% set is_night = future_time >= next_set %}
            {% else %}
              {% set is_night = future_time < next_rise %}
            {% endif %}

            {# Predicted condition #}
            {% set predicted_rank = ([0, current_rank + (shift_per_hour * hour)] | max) %}
            {% set predicted_rank = ([4, predicted_rank] | min) | int %}
            {% if is_night %}
              {% set predicted_condition = night_conditions[predicted_rank] %}
            {% else %}
              {% set predicted_condition = conditions[predicted_rank] %}
            {% endif %}

            {# Temperature: sinusoidal diurnal curve peaking at 14:00, trough at 02:00 #}
            {% set future_hour = future_time.hour + future_time.minute / 60 %}
            {% set phase = (future_hour - 14) / 24 * 2 * pi %}
            {% set curve_temp = t_mean + t_amp * cos(phase) %}

            {# Blend: near hours favor current temp, far hours favor curve #}
            {% set blend = (hour - 1) / 5 %}
            {% set predicted_temp = temp * (1 - blend) + curve_temp * blend %}

            {% set forecast.items = forecast.items + [{
              'datetime': future_time.isoformat(),
              'condition': predicted_condition,
              'temperature': predicted_temp | round(1),
              'humidity': humidity | int
            }] %}
          {% endfor %}
          {{ forecast.items }}