climate:
  - platform: generic_thermostat
    name: Badkamer Verwarming
    unique_id: badkamer_verwarming
    heater: switch.badkamer_verwarming
    target_sensor: sensor.badkamer_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Gameroom Verwarming
    unique_id: gameroom_verwarming
    heater: switch.gameroom_verwarming
    target_sensor: sensor.gameroom_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Kantoor Verwarming
    unique_id: kantoor_verwarming
    heater: switch.kantoor_verwarming
    target_sensor: sensor.kantoor_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Sauna Verwarming
    unique_id: sauna_verwarming
    heater: switch.sauna_verwarming
    target_sensor: sensor.sauna_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Slaapkamer Verwarming
    unique_id: slaapkamer_verwarming
    heater: switch.slaapkamer_verwarming
    target_sensor: sensor.slaapkamer_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Woonkamer Verwarming
    unique_id: woonkamer_verwarming
    heater: switch.woonkamer_verwarming
    target_sensor: sensor.woonkamer_thermostaat_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
sensor:
  - platform: statistics
    name: Outdoor Temperature
    entity_id: sensor.ecowitt_outdoor_temperature
    unique_id: outdoor_temperature
    state_characteristic: median
    max_age:
      hours: 24
schedule:
  badkamer_klimaat:
    name: "Badkamer Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    friday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
  gameroom_klimaat:
    name: "Gameroom Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    friday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
  kantoor_klimaat:
    name: "Kantoor Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    friday:
      - from: "06:00:00"
        to: "18:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
  sauna_klimaat:
    name: "Sauna Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    friday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 20
          target_temp_low_normal: 21
          target_temp_low_cold: 22
  slaapkamer_klimaat:
    name: "Slaapkamer Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 22
          target_temp_high_normal: 23
          target_temp_high_cold: 24
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
  woonkamer_klimaat:
    name: "Woonkamer Klimaat"
    icon: mdi:thermostat-auto
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    saturday:
      - from: "06:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
    sunday:
      - from: "06:00:00"
        to: "24:00:00"
        data:
          target_temp_high_hot: 24
          target_temp_high_normal: 25
          target_temp_high_cold: 26
          target_temp_low_hot: 19
          target_temp_low_normal: 20
          target_temp_low_cold: 21
