sensor:
  - platform: statistics
    name: "Outdoor Luminosity"
    unique_id: outdoor_luminosity
    entity_id: sensor.roof_terrace_sensor_illuminance
    state_characteristic: mean
    max_age:
      minutes: 5
    precision: 0
  - platform: statistics
    name: "Outdoor Temperature Max"
    unique_id: outdoor_temperature_max
    entity_id: sensor.roof_terrace_sensor_temperature
    state_characteristic: value_max
    max_age:
      hours: 96
    precision: 2
  - platform: statistics
    name: "Outdoor Temperature Min"
    unique_id: outdoor_temperature_min
    entity_id: sensor.roof_terrace_sensor_temperature
    state_characteristic: value_min
    max_age:
      hours: 168
    precision: 2
  - platform: statistics
    name: "Outdoor Temperature Mean"
    unique_id: outdoor_temperature_mean
    entity_id: sensor.roof_terrace_sensor_temperature
    state_characteristic: mean
    max_age:
      hours: 168
    precision: 2

climate:
  - platform: generic_thermostat
    name: Bathroom Heating
    unique_id: bathroom_heating
    heater: switch.bathroom_heating
    target_sensor: sensor.bathroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Gameroom Heating
    unique_id: gameroom_heating
    heater: switch.gameroom_heating
    target_sensor: sensor.gameroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Office Heating
    unique_id: office_heating
    heater: switch.office_heating
    target_sensor: sensor.office_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Gym Heating
    unique_id: gym_heating
    heater: switch.gym_heating
    target_sensor: sensor.gym_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Bedroom Heating
    unique_id: bedroom_heating
    heater: switch.bedroom_heating
    target_sensor: sensor.bedroom_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
  - platform: generic_thermostat
    name: Living Room Heating
    unique_id: living_room_heating
    heater: switch.living_room_heating
    target_sensor: sensor.living_room_temperature
    min_temp: 16
    max_temp: 22
    ac_mode: false
    target_temp_step: 0.5
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      hours: 1
schedule:
  bathroom_climate:
    name: "Bathroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
  gameroom_climate:
    name: "Gameroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "18:00:00"
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
    friday:
      - from: "06:00:00"
        to: "18:00:00"
  office_climate:
    name: "Office Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "18:00:00"
    tuesday:
      - from: "06:00:00"
        to: "18:00:00"
    wednesday:
      - from: "06:00:00"
        to: "18:00:00"
    thursday:
      - from: "06:00:00"
        to: "18:00:00"
    friday:
      - from: "06:00:00"
        to: "18:00:00"
  gym_climate:
    name: "Gym Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
  bedroom_climate:
    name: "Bedroom Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    saturday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
    sunday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "20:00:00"
        to: "24:00:00"
  living_room_climate:
    name: "Living Room Climate"
    icon: mdi:thermostat-cog
    monday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    tuesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    wednesday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    thursday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    friday:
      - from: "06:00:00"
        to: "10:00:00"
      - from: "16:00:00"
        to: "24:00:00"
    saturday:
      - from: "06:00:00"
        to: "24:00:00"
    sunday:
      - from: "06:00:00"
        to: "24:00:00"
template:
  - sensor:
      - name: "Cooling"
        unique_id: cooling
        state: >
          {% set climates = [
            states('climate.gameroom_cooling'),
            states('climate.office_cooling'),
            states('climate.bedroom_cooling'),
            states('climate.living_room_cooling'),
          ] %}
          {{ climates | select('eq', 'cool') | list | count }}
        icon: mdi:snowflake-thermometer
  - sensor:
      - name: "Heating"
        unique_id: heating
        icon: mdi:sun-thermometer
        state: >
          {% set climates = [
            states('climate.bathroom_heating'),
            states('climate.gameroom_heating'),
            states('climate.office_heating'),
            states('climate.gym_heating'),
            states('climate.bedroom_heating'),
            states('climate.living_room_heating'),
          ] %}
          {{ climates | select('eq', 'heat') | list | count }}
  - sensor:
      - name: "Daylight Duration"
        unique_id: daylight_duration
        unit_of_measurement: "h"
        state_class: measurement
        state: >
          {% set sunrise = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
          {% set sunset = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
          {% if sunrise < sunset %}
            {{ ((sunset - sunrise) / 3600) | round(2) }}
          {% else %}
            {{ ((sunset + 86400 - sunrise) / 3600) | round(2) }}
          {% endif %}
        icon: mdi:sun-clock
  - sensor:
      - name: "Climate Heat Stress"
        unique_id: climate_heat_stress
        unit_of_measurement: "%"
        state_class: measurement
        state: >
          {% set T = states('sensor.roof_terrace_sensor_temperature') | float(0) %}
          {% set lux = states('sensor.roof_terrace_sensor_illuminance') | float(0) %}
          {% set solar = lux / 100 %}
          {% set rh = states('sensor.roof_terrace_sensor_humidity') | float(0) %}
          {% set wind = states('sensor.roof_terrace_sensor_wind_speed') | float(0) %}
          {% set precipitation = states('sensor.roof_terrace_sensor_precipitation') | float(0) %}

          {% set base = T + (solar / 100) + (rh / 10) %}
          {% set cooled = base - (wind / 2) %}
          {% set adjusted = cooled - (3 if precipitation > 0 else 0) %}

          {% set min_val = 18 %}
          {% set max_val = 42 %}
          {% set scaled = ((adjusted - min_val) / (max_val - min_val)) %}

          {# Tuned sigmoid curve using Euler's number approximation #}
          {% set sigmoid = 1 / (1 + (2.71828 ** (-4 * (scaled - 0.5)))) %}
          {% set percent = sigmoid * 100 %}
          {{ [percent, 0] | max | round(0) }}
        icon: mdi:weather-sunny-alert
  - sensor:
      - name: "Climate Humidex"
        unique_id: climate_humidex
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set T = states('sensor.roof_terrace_sensor_temperature') | float(0) %}
          {% set RH = states('sensor.roof_terrace_sensor_humidity') | float(0) %}
          {# Calculate dewpoint using Magnus formula #}
          {% set a = 17.27 %}
          {% set b = 237.7 %}
          {% set alpha = (a * T) / (b + T) + (RH / 100) | log %}
          {% set Td = (b * alpha) / (a - alpha) %}
          {% set e = 6.11 * (2.718281828 ** (5417.7530 * ((1/273.15) - (1/(273.15 + Td))))) %}
          {{ (T + (0.5555 * (e - 10))) | round(1) }}
        icon: mdi:thermometer-water
  - sensor:
      - name: "Climate Luminosity"
        unique_id: climate_luminosity
        state: >
          {% set lux = states('sensor.outdoor_luminosity') | int(0) %}
          {% if lux < 1000 %}
            dark
          {% elif lux < 5000 %}
            low
          {% elif lux < 20000 %}
            mid
          {% elif lux < 50000 %}
            high
          {% else %}
            peak
          {% endif %}
        icon: mdi:white-balance-sunny
  - sensor:
      - name: "Climate Mode"
        unique_id: climate_mode
        state: >
          {% set hs = states('sensor.climate_heat_stress') | float(0) %}
          {% set humidex = states('sensor.climate_humidex') | float(0) %}
          {% set daylight_h = states('sensor.daylight_duration') | float(0) %}
          {% set min7 = states('sensor.outdoor_temperature_min') | float(0) %}
          {% set max4 = states('sensor.outdoor_temperature_max') | float(0) %}

          {% set warm_enter_humidex = 29 %}
          {% set warm_exit_humidex  = 27 %}
          {% set warm_enter_hs = 75 %}
          {% set warm_exit_hs  = 65 %}
          {% set cold_enter_humidex = 17 %}
          {% set cold_exit_humidex  = 19 %}
          {% set cold_enter_hs = 25 %}
          {% set cold_exit_hs  = 35 %}

          {% set last = states('sensor.climate_mode') | lower %}
          {% if last in ['unknown','unavailable','none',''] %}
            {% set last = 'mild' %}
          {% endif %}

          {% if last == 'warm' %}
            {% if (humidex <= warm_exit_humidex and hs <= warm_exit_hs) %}
              {% if humidex <= cold_enter_humidex and hs <= cold_enter_hs and min7 <= 10 %}
                cold
              {% else %}
                mild
              {% endif %}
            {% else %}
              warm
            {% endif %}

          {% elif last == 'cold' %}
            {% if (humidex >= cold_exit_humidex or hs >= cold_exit_hs) %}
              {% if (humidex >= warm_enter_humidex or hs >= warm_enter_hs)
                    and max4 >= 25
                    and daylight_h > 13 %}
                warm
              {% else %}
                mild
              {% endif %}
            {% else %}
              cold
            {% endif %}

          {% else %}
            {% if (humidex >= warm_enter_humidex or hs >= warm_enter_hs)
                  and max4 >= 25
                  and daylight_h > 13 %}
              warm
            {% elif humidex <= cold_enter_humidex and hs <= cold_enter_hs and min7 <= 10 %}
              cold
            {% else %}
              mild
            {% endif %}
          {% endif %}
        icon: mdi:sun-snowflake-variant